FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-4.23 AS builder
WORKDIR /workspace
COPY . .
RUN go build -mod=vendor -o gcp-workload-identity-federation-webhook main.go
FROM registry.ci.openshift.org/ocp/4.23:base-rhel9
COPY --from=builder /workspace/gcp-workload-identity-federation-webhook /usr/bin
